---
abstract: 'Base class for REST resources'
author:
  - 'Audrey Tang <audreyt@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: cc0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-REST
no_index:
  directory:
    - inc
    - t
requires:
  Class::Struct: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  URI: 0
  perl: 5.6.0
version: '0.011'
