name: WWW-REST
version: 0.01
abstract: Base class for REST resources
author: Autrijus Tang (autrijus@autrijus.org)
license: unknown
distribution_type: module
build_requires:
  Test::More: 0
requires:
  URI: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Class::Struct: 0
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.26
